### ISSUE TITLE
Создать свои файлы шрифтов ГОСТ 2.304-81 с корректными данными для XeTeX

### ISSUE THREAD

**Issue by sergey-s-betke** [sergey-s-betke/ITG.1C.Metrolog.LogBook#55]
Все доступные на сегодня шрифты имеют те или иные изъяны в плане совместимости с TeX. В некоторых нет математики, в других высота символов "пляшет", в третьих - кодировка математики некорректна, и во всех - нет параметров высоты и глубины для математических символов, параметров дробей и степеней для TeX.

Поэтому следует выбрать за основу тот или иной шрифт и создать именно те шрифты, что нам необходимы.

**Comment by sergey-s-betke** [comment]
Хорош в плане правильного масштаба для "рисования" MipGost.ttf. Но в нём, как выясняется, далеко не все глифы нарисованы без ошибок. Есть пересечения, незакрытые контуры...

Хорош и шрифт от Ascon. Глифы прорисованы более аккуратно, но нет греческого алфавита и математики.

Всё-таки, склоняюсь к варианту взять за основу mipgost, удалить сразу все ненужные глифы с акцентами (потребуются - добавлю), и его и исправлять.

Итак, план:
- [x] создать заготовку проекта на fontforge
- [x] заполнить аттрибуты нашего шрифта, сгенерировать шрифт. Пробовать генерировать стоит .oft, потому как в .ttf xetex не поддерживает кернинг почему-то... (по-крайней мере, fontspec об этом говорит)
- [x] выяснить с масштабной сеткой - связана ли она каким-либо образом с конечным размером шрифта или нет. Можем ли мы действительно использовать ту сетку, что предлагает нам mipgost.
- [x] попробовать задать масштаб в шрифте таким образом, чтобы дополнительного масштабирования в tex уже не потребовалось. (#48). Предварительно - всё возможно. Нужно правильно указать размер `em` в шрифте в единицах координат шрифта. - не возможно, ниже описал подробнее.
- [ ] заполнить предельные размеры шрифта по ГОСТ 2.304-81. 
- [ ] уточнить, можно ли задать размерный ряд в шрифте. И, если можно, - задать его.
- [ ] заполнить tex аттрибуты шрифта (высоты линий, и так далее), проверить их в работе уже без дополнительной настройки в tex (#52)
- [x] попробовать изменить tex высоту и глубину радикала в шрифте без изменения его положения в шрифте (чтобы обеспечить его использование и в MS Word, и в tex), не забыть при этом про дополнительные параметры xetex, определяющие, будет ли xetex использовать действительные параметры глифа или будет использовать общие параметры для всего шрифта. (#51)
- [ ] задать положение индексов
- [x] убрать все лишние символы на первом этапе (с акцентами, в частности)
- [x] отладить символы (все выявляемые ошибки), упростить контуры по примеру Ascon
- [ ] добавить необходимую математику
- [ ] добавить несколько вариантов для символа `3`, протестировать их  использование в tex, добавить соответствующую опцию в пакет.
- [ ] задать горизонтальный кернинг
- [ ] подумать над лигатурами для римских цифр
- [ ] добавить варианты начертания римских цифр (с ограничивающими линиями)
- [ ] добавить отдельно кернинг для символов в римских цифрах

**Comment by sergey-s-betke** [comment]
[Обзор инструментов для создания / редактирования шрифтов.](<http://habrahabr.ru/post/51130/>)

**Comment by sergey-s-betke** [comment]
O true type инструкциях - <http://www.microsoft.com/typography/otspec/ttinst.htm>

**Comment by sergey-s-betke** [comment]
Несколько символов для теста добавил. Теперь имеет смысл добавить скобки (математические), и радикал, чтобы проверить математику.

**Comment by sergey-s-betke** [comment]
При установке fontforge следует добавить поддержку кириллических раскладок клавиатуры руками - https://github.com/fontforge/fontforge/issues/1729.

**Comment by sergey-s-betke** [comment]
Удалось определить параметры для символа радикала, не изменяя реального положения символа в шрифте. Для этого кроме параметров для самого символа необходимо задать math info. Протестировал, радикал отображается корректно. И линия над аргументом так же.

**Comment by sergey-s-betke** [comment]
Есть проблема с масштабом шрифта и размерами его. В шрифтах TeX `\f@size` равно `em`. И мне следует добиться того же. Однако, у моего шрифта эти значения различаются в 1.19 раза...

**Comment by sergey-s-betke** [comment]
Проблема с `em` была простая - у меня при загрузке шрифта ему назначался фиксированный размерный ряд, поэтому у меня и возникало несоответствие.

**Comment by sergey-s-betke** [comment]
Итак, `em` соответствует `\f@size` (и параметрам `\fontsize` соответственно). Но следует понимать, что теперь `em` не равно `h+k`, теперь к этой величине ещё добавлены ещё и акценты. Поэтому решение #48 следует пересмотреть.

**Comment by sergey-s-betke** [comment]
Имею проблему при расчёте масштаба шрифта через `ex` (`c`) - получаю при загрузке в xetex неверное значение `ex` для шрифта. `em` - корректное значение (как установил, так и получил), а `ex` - нет...

**Comment by sergey-s-betke** [comment]
Похоже, для `ex` принудительно используется автоопределение - https://github.com/fontforge/fontforge/issues/1959, которое работает в свою очередь по строчным буквам, которых у меня на момент тестирования просто нет. Попробую добавить собственно букву `x`.

Это подтверждается рекомендациями MS: http://www.microsoft.com/typography/otspec/os2.htm#xh.

Странно другое: я явно задал в таблице OS/2 x height, но при этом при генерации .otf шрифта сведения берутся явно не из этой таблицы.

**Comment by sergey-s-betke** [comment]
Всё так и есть. Стоило добавить символ `x` - и получил сразу корректный размер `ex`. Итого - fontforge использует автоопределение `ex` и игнорирует сведения в OS/2 `x height`.

**Comment by sergey-s-betke** [comment]
Масштабная сетка связана со шрифтом. Но избежать масштабирования в tex не получится. Точнее - можно, но не стоит. Сейчас я масштабирую через `ex` (`c`). Вычислять `h` через `em`, а не через `ex` - будет неправильно, просто потому, что `em` может содержать дополнительные зазоры над символами и под ними, а `ex` от этого не зависит. Поэтому оставляем вычисление fontsize (`em`) через ex с предварительным замером этого соотношения.

**Comment by sergey-s-betke** [comment]
Теперь приступаю к переносу всех символов в свой шрифт. Пока только цифры, латиницу и кириллицу, без математики.

**Comment by sergey-s-betke** [comment]
О переносах, тире и прочем - http://en.wikipedia.org/wiki/Dash.

**Comment by sergey-s-betke** [comment]
Вынес создание шрифтов в отдельный проект и репозиторий - https://github.com/Metrolog/Font.GOST2.304-81.
